// Generated by CoffeeScript 1.3.3
(function() {
  var $body, $html, $win, Overlay,
    __slice = [].slice;

  $win = $(window);

  $html = $('html');

  $body = $('body');

  $.getPageSize || ($.getPageSize = function() {
    var page_h, page_w, w, win_h, win_w, x_scroll, y_scroll, _ref, _ref1;
    _ref = (function() {
      switch (false) {
        case !(window.innerHeight && window.scrollMaxY):
          return [window.innerWidth + window.scrollMaxX, window.innerHeight + window.scrollMaxY];
        case !(document.body.scrollHeight > document.body.offsetHeight):
          return [document.body.scrollWidth, document.body.scrollHeight];
        default:
          return [document.body.offsetWidth, document.body.offsetHeight];
      }
    })(), x_scroll = _ref[0], y_scroll = _ref[1];
    _ref1 = (function() {
      var _ref1, _ref2;
      switch (false) {
        case !self.innerHeight:
          w = ((_ref1 = document.documentElement) != null ? _ref1.clientWidth : void 0) || self.innerWidth;
          return [w, self.innerHeight];
        case !((_ref2 = document.documentElement) != null ? _ref2.clientHeight : void 0):
          return [document.documentElement.clientWidth, document.documentElement.clientHeight];
        case !document.body:
          return [document.body.clientWidth, document.body.clientHeight];
      }
    })(), win_w = _ref1[0], win_h = _ref1[1];
    page_w = x_scroll < win_w ? x_scroll : win_w;
    page_h = y_scroll < win_h ? win_h : y_scroll;
    return {
      page: {
        width: page_w,
        height: page_h
      },
      window: {
        width: win_w,
        height: win_h
      }
    };
  });

  $.Overlay = Overlay = (function() {

    Overlay.uid = 0;

    Overlay.all = $([]);

    Overlay.page_size = [];

    Overlay.create = function(settings) {
      return new Overlay(settings);
    };

    function Overlay(settings) {
      var close_on_click, page_size, self;
      self = this;
      this._opening = false;
      this._opend = false;
      this.settings = $.extend({
        bg_color: "#000000",
        opacity: 0.5,
        fade_speed: 400,
        overlay_class: "pageOverlay",
        close_on_click: true
      }, settings);
      page_size = Overlay.page_size = $.getPageSize();
      this.id = this.settings.overlay_class + Overlay.uid++;
      this.overlay = $('<div></div>').attr({
        "class": this.settings.overlay_class,
        id: this.id
      }).css({
        display: "none",
        width: page_size.window.width,
        height: page_size.page.height,
        position: "absolute",
        top: 0,
        left: 0,
        backgroundColor: this.settings.bg_color,
        opacity: 0
      });
      $win.off('resize.overlay_resize').on('resize.overlay_resize', function(ev) {
        page_size = Overlay.page_size = $.getPageSize();
        return Overlay.all.css({
          width: page_size.window.width,
          height: page_size.page.height
        });
      });
      if (close_on_click = this.settings.close_on_click) {
        this.overlay.click(function(ev) {
          if (close_on_click === true) {
            return self.close();
          } else {
            return self.close.apply(self, $.makeArray(close_on_click));
          }
        });
      }
      this.overlay.appendTo($('body'));
      Overlay.all = Overlay.all.add(this.overlay);
    }

    Overlay.prototype.open = function(speed, callback) {
      var self, _ref;
      self = this;
      if (!this._opening) {
        if (!callback && $.isFunction(speed)) {
          _ref = [null, speed], speed = _ref[0], callback = _ref[1];
        }
        this.selects = $('select:visible').hide();
        this._opening = true;
        return this.overlay.show().fadeTo(speed || this.settings.fade_speed, this.settings.opacity, function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          this._opend = true;
          if (callback && $.isFunction(callback)) {
            return callback.apply(this, args);
          }
        });
      }
    };

    Overlay.prototype.close = function(speed, callback) {
      var self, _ref;
      self = this;
      if (this._opening) {
        if (!callback && $.isFunction(speed)) {
          _ref = [null, speed], speed = _ref[0], callback = _ref[1];
        }
        this._opend = false;
        return this.overlay.stop().fadeTo(speed || this.settings.fade_speed, 0, function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          self.overlay.hide();
          self.selects.show();
          self._opening = false;
          if (callback && $.isFunction(callback)) {
            return callback.apply(this, args);
          }
        });
      }
    };

    Overlay.prototype.opening = function() {
      return this._opening;
    };

    Overlay.prototype.opend = function() {
      return this._opend;
    };

    return Overlay;

  })();

}).call(this);
